# Header
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
sidebar: right
widgets:
- tag
- recent_posts
- archive


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /images/favicon1.png
twitter:
google_plus:
fb_admins:
fb_app_id:
codepen: https://codepen.io/lucas-j-k/
github: https://github.com/lucas-j-k


# config the sass renderer module
node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false
